/*  This file is part of GeckoCIRCUITS. Copyright (C) ETH Zurich, Gecko-Simulations GmbH
 *
 *  GeckoCIRCUITS is free software: you can redistribute it and/or modify it under 
 *  the terms of the GNU General Public License as published by the Free Software 
 *  Foundation, either version 3 of the License, or (at your option) any later version.
 *
 *  GeckoCIRCUITS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 *  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *  PURPOSE.  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with
 *  GeckoCIRCUITS.  If not, see <http://www.gnu.org/licenses/>.
 */
package ch.technokrat.gecko.geckocircuits.control;

import ch.technokrat.gecko.geckocircuits.circuit.NameAlreadyExistsException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

public class DialogMuxDemux extends javax.swing.JDialog {

    private final RegelBlock _regelBlock;

    /** Creates new form DialogExterna */
    public DialogMuxDemux(final RegelBlock regelBlock) {
        super((JFrame) null, true);
        this.setLocationByPlatform(true);

        initComponents();
        jTextFieldIdString.setText(regelBlock.getStringID());
        _regelBlock = regelBlock;                        

        if (_regelBlock instanceof ReglerMUX) {
            jSpinnerPortNumber.setValue(new Integer(regelBlock.XIN.size()));
        }
        
        if (_regelBlock instanceof ReglerDemux) {
            jSpinnerPortNumber.setValue(new Integer(regelBlock.YOUT.size()));
        }                    
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerPortNumber = new javax.swing.JSpinner();
        jTextFieldIdString = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("External interface");
        setResizable(false);

        jLabel1.setText("Name / Label:");

        jLabel2.setText("Port width:");

        jSpinnerPortNumber.setModel(new javax.swing.SpinnerNumberModel(1, 1, 40, 1));
        jSpinnerPortNumber.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerPortNumberStateChanged(evt);
            }
        });

        jTextFieldIdString.setText("jTextField1");
        jTextFieldIdString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdStringActionPerformed(evt);
            }
        });
        jTextFieldIdString.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextFieldIdStringPropertyChange(evt);
            }
        });
        jTextFieldIdString.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIdStringKeyTyped(evt);
            }
        });

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIdString, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIdString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinnerPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//NOPMD//GEN-FIRST:event_jButtonOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jTextFieldIdStringPropertyChange(java.beans.PropertyChangeEvent evt) {//NOPMD//GEN-FIRST:event_jTextFieldIdStringPropertyChange
        

    }//GEN-LAST:event_jTextFieldIdStringPropertyChange

    private void jTextFieldIdStringKeyTyped(java.awt.event.KeyEvent evt) {//NOPMD//GEN-FIRST:event_jTextFieldIdStringKeyTyped
        if (this.isVisible()) {
            try {
                _regelBlock.setNewNameChecked(jTextFieldIdString.getText());
            } catch (NameAlreadyExistsException ex) {
                Logger.getLogger(DialogMuxDemux.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTextFieldIdStringKeyTyped

    private void jSpinnerPortNumberStateChanged(javax.swing.event.ChangeEvent evt) {//NOPMD//GEN-FIRST:event_jSpinnerPortNumberStateChanged
        if (_regelBlock instanceof ReglerToEXTERNAL) {
            ((ReglerToEXTERNAL) _regelBlock).setInputTerminalNumber((Integer) jSpinnerPortNumber.getValue());
        }

        if (_regelBlock instanceof ReglerFromEXTERNAL) {
            ((ReglerFromEXTERNAL) _regelBlock).setOutputTerminalNumber((Integer) jSpinnerPortNumber.getValue());
        }
        
        if(_regelBlock instanceof ReglerMUX) {
            ((ReglerMUX) _regelBlock).setInputTerminalNumber((Integer) jSpinnerPortNumber.getValue());
        }
        
        if(_regelBlock instanceof ReglerDemux) {
            ((ReglerDemux) _regelBlock).setOutputTerminalNumber((Integer) jSpinnerPortNumber.getValue());
        }
        
        
        
    }//GEN-LAST:event_jSpinnerPortNumberStateChanged

    private void jTextFieldIdStringActionPerformed(java.awt.event.ActionEvent evt) {//NOPMD//GEN-FIRST:event_jTextFieldIdStringActionPerformed
        
        try {
            _regelBlock.setNewNameChecked(jTextFieldIdString.getText());
        } catch (NameAlreadyExistsException ex) {
            ex.printStackTrace();
        }                
    }//GEN-LAST:event_jTextFieldIdStringActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinnerPortNumber;
    private javax.swing.JTextField jTextFieldIdString;
    // End of variables declaration//GEN-END:variables
}
