/*  This file is part of GeckoCIRCUITS. Copyright (C) ETH Zurich, Gecko-Simulations GmbH
 *
 *  GeckoCIRCUITS is free software: you can redistribute it and/or modify it under 
 *  the terms of the GNU General Public License as published by the Free Software 
 *  Foundation, either version 3 of the License, or (at your option) any later version.
 *
 *  GeckoCIRCUITS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 *  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *  PURPOSE.  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with
 *  GeckoCIRCUITS.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * JPanel to display polynomial fractions
 */
package ch.technokrat.gecko.geckocircuits.control;

import java.awt.Graphics;
import javax.swing.JLabel;

/**
 *
 * @author andy
 */
public final class FractionPrinter extends javax.swing.JPanel {
    private static final double STRING_LENTH_FAC = 0.85;
    
    public FractionPrinter() {
        super();
        initComponents();
    }

    public void hsSetText(final String newText) {
        jLabelHs.setText(newText);
    }
    
    public void setNumeratorText(final String newText) {
        jLabelNumerator.setText(newText);
        jLabelLine.repaint();
    }
    
    public void setDenominatorText(final String newText) {
        jLabelDenom.setText(newText);
        jLabelLine.repaint();
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    //CHECKSTYLE:OFF
    @SuppressWarnings("PMD")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTFPoleView = new javax.swing.JPanel();
        jLabelHs = new javax.swing.JLabel();
        jLabelNumerator = new javax.swing.JLabel();
        jLabelLine = new JLabelLine();
        jLabelDenom = new javax.swing.JLabel();

        jPanelTFPoleView.setBorder(javax.swing.BorderFactory.createTitledBorder("Transfer Function"));

        jLabelHs.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelHs.setText("H(s) = ");

        jLabelNumerator.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelNumerator.setText("jLabel4");
        jLabelNumerator.setPreferredSize(null);

        jLabelLine.setFont(new java.awt.Font("Ubuntu", 1, 5)); // NOI18N

        jLabelDenom.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelDenom.setText("jLabel5");
        jLabelDenom.setPreferredSize(null);

        javax.swing.GroupLayout jPanelTFPoleViewLayout = new javax.swing.GroupLayout(jPanelTFPoleView);
        jPanelTFPoleView.setLayout(jPanelTFPoleViewLayout);
        jPanelTFPoleViewLayout.setHorizontalGroup(
            jPanelTFPoleViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTFPoleViewLayout.createSequentialGroup()
                .addComponent(jLabelHs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTFPoleViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelTFPoleViewLayout.createSequentialGroup()
                        .addGroup(jPanelTFPoleViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNumerator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 447, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTFPoleViewLayout.setVerticalGroup(
            jPanelTFPoleViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTFPoleViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTFPoleViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelTFPoleViewLayout.createSequentialGroup()
                        .addComponent(jLabelNumerator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLine, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelHs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTFPoleView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTFPoleView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDenom;
    private javax.swing.JLabel jLabelHs;
    private javax.swing.JLabel jLabelLine;
    private javax.swing.JLabel jLabelNumerator;
    private javax.swing.JPanel jPanelTFPoleView;
    // End of variables declaration//GEN-END:variables
    

    class JLabelLine extends JLabel {

        @Override
        public void paint(Graphics g) {
            super.paint(g);            
            int width = Math.max(jLabelDenom.getWidth(), jLabelNumerator.getWidth()); 
            g.drawLine(0,6,width,6);
        }
        
    }            
}
