/*  This file is part of GeckoCIRCUITS. Copyright (C) ETH Zurich, Gecko-Simulations GmbH
 *
 *  GeckoCIRCUITS is free software: you can redistribute it and/or modify it under 
 *  the terms of the GNU General Public License as published by the Free Software 
 *  Foundation, either version 3 of the License, or (at your option) any later version.
 *
 *  GeckoCIRCUITS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 *  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *  PURPOSE.  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with
 *  GeckoCIRCUITS.  If not, see <http://www.gnu.org/licenses/>.
 */
package ch.technokrat.gecko.geckocircuits.newscope;

import ch.technokrat.gecko.i18n.resources.I18nKeys;
import java.awt.Component;
import javax.swing.border.TitledBorder;

/**
 *
 * @author andy
 */
public class JPanelLineProperties extends javax.swing.JPanel {

    private LineSettable _lineSettable;
    private Component _redrawComponent;

    public JPanelLineProperties() {
        super();
        initComponents();
        setBorder(new TitledBorder(I18nKeys.LINE_PROPERTIES.getTranslation()));
        _lineSettable = null;
        _redrawComponent = null;
    }

    public void init(final LineSettable lineSettable, final Component redrawComponent) {
        _lineSettable = lineSettable;

        for (GeckoColor color : GeckoColor.values()) {
            jComboBoxColor.addItem(color);
        }
        for (GeckoLineStyle lineStyle : GeckoLineStyle.values()) {
            jComboBoxStroke.addItem(lineStyle);
        }

        if (lineSettable instanceof AbstractCurve) {
            for (GeckoLineType type : GeckoLineType.values()) {
                jComboBoxType.addItem(type);
            }
            jComboBoxType.setSelectedItem( ((AbstractCurve)lineSettable).getLineType());
        } else {
            jComboBoxType.setVisible(false);
            jLabelLineType.setVisible(false);
            this.revalidate();
        }


        jComboBoxStroke.setSelectedIndex(_lineSettable.getStroke().ordinal());
        jComboBoxColor.setSelectedIndex(_lineSettable.getColor().ordinal());
        jSpinnerTransp.setValue(_lineSettable.getTransparency());

        // careful: this is by intention the last assignment!
        _redrawComponent = redrawComponent;
    }

    private void repaintComponent() {
        if (_redrawComponent != null) {
            _redrawComponent.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxStroke = new javax.swing.JComboBox();
        jComboBoxColor = new javax.swing.JComboBox();
        jSpinnerTransp = new javax.swing.JSpinner();
        jLabelLineType = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Line style:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Line color:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Transparency:");

        jComboBoxStroke.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBoxStroke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStrokeActionPerformed(evt);
            }
        });

        jComboBoxColor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBoxColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxColorActionPerformed(evt);
            }
        });

        jSpinnerTransp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jSpinnerTransp.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(0.0f), Float.valueOf(1.0f), Float.valueOf(0.1f)));
        jSpinnerTransp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerTranspStateChanged(evt);
            }
        });

        jLabelLineType.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelLineType.setText("Line type:");

        jComboBoxType.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelLineType)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxColor, 0, 122, Short.MAX_VALUE)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerTransp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxStroke, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxStroke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLineType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerTransp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("PMD")
    private void jSpinnerTranspStateChanged(javax.swing.event.ChangeEvent evt) {//NOPMD//GEN-FIRST:event_jSpinnerTranspStateChanged
        if (_redrawComponent != null) {
            _lineSettable.setTransparency((Float) jSpinnerTransp.getValue());
        }
        repaintComponent();
    }//GEN-LAST:event_jSpinnerTranspStateChanged

    @SuppressWarnings("PMD")
    private void jComboBoxColorActionPerformed(java.awt.event.ActionEvent evt) {//NOPMD//GEN-FIRST:event_jComboBoxColorActionPerformed
        if (_redrawComponent != null) {
            _lineSettable.setColor(GeckoColor.getFromOrdinal(jComboBoxColor.getSelectedIndex()));
        }
        repaintComponent();
    }//GEN-LAST:event_jComboBoxColorActionPerformed

    @SuppressWarnings("PMD")
    private void jComboBoxStrokeActionPerformed(java.awt.event.ActionEvent evt) {//NOPMD//GEN-FIRST:event_jComboBoxStrokeActionPerformed
        if (_redrawComponent != null) {
            _lineSettable.setStroke(GeckoLineStyle.getFromOrdinal(jComboBoxStroke.getSelectedIndex()));
        }
        repaintComponent();
    }//GEN-LAST:event_jComboBoxStrokeActionPerformed

    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeActionPerformed
        if (_redrawComponent != null && _lineSettable instanceof AbstractCurve) {
            ((AbstractCurve) _lineSettable).setLineType((GeckoLineType) jComboBoxType.getSelectedItem());
        }
        repaintComponent();
    }//GEN-LAST:event_jComboBoxTypeActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxColor;
    private javax.swing.JComboBox jComboBoxStroke;
    private javax.swing.JComboBox jComboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelLineType;
    public javax.swing.JSpinner jSpinnerTransp;
    // End of variables declaration//GEN-END:variables
}
