/*  This file is part of GeckoCIRCUITS. Copyright (C) ETH Zurich, Gecko-Simulations AG
 *
 *  GeckoCIRCUITS is free software: you can redistribute it and/or modify it under 
 *  the terms of the GNU General Public License as published by the Free Software 
 *  Foundation, either version 3 of the License, or (at your option) any later version.
 *
 *  GeckoCIRCUITS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 *  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *  PURPOSE.  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with
 *  GeckoCIRCUITS.  If not, see <http://www.gnu.org/licenses/>.
 */
package ch.technokrat.gecko.geckocircuits.circuit.circuitcomponents;

import ch.technokrat.gecko.geckocircuits.circuit.NameAlreadyExistsException;
import ch.technokrat.gecko.geckocircuits.control.SubCircuitSheet;
import ch.technokrat.gecko.i18n.resources.I18nKeys;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author andreas
 */
public class DialogSubCktSettings extends javax.swing.JDialog {

    private final SubcircuitBlock _subBlock;
    private final SubCircuitSheet _subSheet;
    private final boolean _initDone;

    /**
     * Creates new form DialogSheetSettings
     */
    public DialogSubCktSettings(java.awt.Frame parent, boolean modal,
            final SubcircuitBlock subBlock) {
        super(parent, modal);
        initComponents();
        _subBlock = subBlock;
        setTitle(I18nKeys.SUBCIRCUIT + " " + I18nKeys.SETTINGS);
        getRootPane().setDefaultButton(jButtonOk);
        setResizable(false);
        jSpinnerBlockX.setValue(_subBlock._blockSizeX.getValue());
        jSpinnerBlockY.setValue(_subBlock._blockSizeY.getValue());
        _subSheet = _subBlock._myCircuitSheet;
        jSpinnerSheetX.setValue(_subSheet._worksheetSize.getSizeX());
        jSpinnerSheetY.setValue(_subSheet._worksheetSize.getSizeY());
        _initDone = true;
        jTextFieldSubName.setText(_subBlock.getStringID());
        jLabelWSSizeX.setText(I18nKeys.WORKSHEET_SIZE.getTranslation() + "X:");
        jLabelWSSizeY.setText(I18nKeys.WORKSHEET_SIZE.getTranslation() + "Y:");
        jLabelSubcircuitName.setText(I18nKeys.SUBCIRCUIT + " " + I18nKeys.NAME + ":");
        jLabelSubcircuitSizeX.setText(I18nKeys.SUBCIRCUIT.getTranslation() + " " + I18nKeys.SIZE.getTranslation() + " X:");
        jLabelSubcircuitSizeY.setText(I18nKeys.SUBCIRCUIT.getTranslation() + " " + I18nKeys.SIZE.getTranslation() + " Y:");
        jButtonOk.setText(I18nKeys.OK.getTranslation());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOk = new javax.swing.JButton();
        jLabelWSSizeX = new javax.swing.JLabel();
        jLabelWSSizeY = new javax.swing.JLabel();
        jLabelSubcircuitSizeX = new javax.swing.JLabel();
        jLabelSubcircuitSizeY = new javax.swing.JLabel();
        jSpinnerSheetX = new javax.swing.JSpinner();
        jSpinnerSheetY = new javax.swing.JSpinner();
        jSpinnerBlockX = new javax.swing.JSpinner();
        jSpinnerBlockY = new javax.swing.JSpinner();
        jLabelSubcircuitName = new javax.swing.JLabel();
        jTextFieldSubName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);

        jButtonOk.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jLabelWSSizeX.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelWSSizeX.setText("Worksheet size X:");

        jLabelWSSizeY.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelWSSizeY.setText("Worksheet size Y:");

        jLabelSubcircuitSizeX.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelSubcircuitSizeX.setText("Subcircuit block size X:");

        jLabelSubcircuitSizeY.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelSubcircuitSizeY.setText("Subcircuit block size Y:");

        jSpinnerSheetX.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jSpinnerSheetX.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(40), Integer.valueOf(20), null, Integer.valueOf(5)));
        jSpinnerSheetX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerSheetXStateChanged(evt);
            }
        });

        jSpinnerSheetY.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jSpinnerSheetY.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(30), Integer.valueOf(20), null, Integer.valueOf(5)));
        jSpinnerSheetY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerSheetYStateChanged(evt);
            }
        });

        jSpinnerBlockX.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jSpinnerBlockX.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSpinnerBlockX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerBlockXStateChanged(evt);
            }
        });

        jSpinnerBlockY.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jSpinnerBlockY.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSpinnerBlockY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerBlockYStateChanged(evt);
            }
        });

        jLabelSubcircuitName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelSubcircuitName.setText("Subcircuit name:");

        jTextFieldSubName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextFieldSubName.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelSubcircuitName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSubName))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelWSSizeY)
                                    .addComponent(jLabelWSSizeX)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelSubcircuitSizeY)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerBlockY))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelSubcircuitSizeX)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSpinnerSheetX, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                            .addComponent(jSpinnerSheetY)
                                            .addComponent(jSpinnerBlockX)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSpinnerBlockX, jSpinnerBlockY, jSpinnerSheetX, jSpinnerSheetY});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWSSizeX)
                    .addComponent(jSpinnerSheetX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWSSizeY)
                    .addComponent(jSpinnerSheetY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSubcircuitSizeX)
                    .addComponent(jSpinnerBlockX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSubcircuitSizeY)
                    .addComponent(jSpinnerBlockY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSubcircuitName)
                    .addComponent(jTextFieldSubName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        try {
            _subBlock.setNewNameCheckedUndoable(jTextFieldSubName.getText());
            this.dispose();
        } catch (NameAlreadyExistsException ex) {
            JOptionPane.showMessageDialog(this,
                    "Object name: " + jTextFieldSubName.getText() + " is already in use!",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE);
            Logger.getLogger(DialogSubCktSettings.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jSpinnerSheetXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerSheetXStateChanged
        
        if(_initDone) {       
            _subBlock._myCircuitSheet._worksheetSize.setNewWorksheetSize((Integer) jSpinnerSheetX.getValue(), (Integer) jSpinnerSheetY.getValue());            
            _subSheet.repaint();
        }
    }//GEN-LAST:event_jSpinnerSheetXStateChanged

    private void jSpinnerBlockXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerBlockXStateChanged
        if (_initDone) {
            _subBlock._blockSizeX.setUserValue((Integer) jSpinnerBlockX.getValue());
            _subBlock.getParentCircuitSheet().repaint();
        }
    }//GEN-LAST:event_jSpinnerBlockXStateChanged

    private void jSpinnerBlockYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerBlockYStateChanged
        if (_initDone) {
            _subBlock._blockSizeY.setUserValue((Integer) jSpinnerBlockY.getValue());
            _subBlock.getParentCircuitSheet().repaint();
        }
    }//GEN-LAST:event_jSpinnerBlockYStateChanged

    private void jSpinnerSheetYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerSheetYStateChanged
        if (_initDone) {            
            _subBlock._myCircuitSheet._worksheetSize.setNewWorksheetSize((Integer) jSpinnerSheetX.getValue(), (Integer) jSpinnerSheetY.getValue());            
            _subSheet.repaint();
        }
    }//GEN-LAST:event_jSpinnerSheetYStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelSubcircuitName;
    private javax.swing.JLabel jLabelSubcircuitSizeX;
    private javax.swing.JLabel jLabelSubcircuitSizeY;
    private javax.swing.JLabel jLabelWSSizeX;
    private javax.swing.JLabel jLabelWSSizeY;
    private javax.swing.JSpinner jSpinnerBlockX;
    private javax.swing.JSpinner jSpinnerBlockY;
    private javax.swing.JSpinner jSpinnerSheetX;
    private javax.swing.JSpinner jSpinnerSheetY;
    private javax.swing.JTextField jTextFieldSubName;
    // End of variables declaration//GEN-END:variables
}
